# ----
# Site

title: Những Cây Thuốc Trong Thiên Nhiên
url: "https://caythuocbamien.com"
baseurl:
google_analytics_key:
newsletter_action:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/binhduongbuy/caythuocbamien)
logo: /siteicon.png
description: Đu đủ và những món ăn ngon làm từ trái đu đủ, phụ kiện làm món ăn đu đủ ngon. sản phẩm từ Odayaka.vn gọi ngay 0899150055 để đặt xe Honda Phú Quốc.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Đu đủ
  links:
    - https://caythuocbamien.com

# -----
# Build

timezone: Etc/UTC

paginate: 10
paginate_path: "/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
      _options:
        content:
          width: 1560
          height: 2000
        featured_image:
          width: 1560
          height: 2000
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

_options:
  author_image:
    width: 400
    height: 400